FIX: BitHandler.__cmp__ on 32bit systems
>>> BitHandler(1, ('FLAG_0',)) < 9223372036854775807
TypeError: int.__cmp__(x,y) requires y to be a 'int', not a 'long'